-- Ferramentas administrativas para testes, dados demonstrativos e auditoria.

begin;

-- Dados DEMO existem apenas para exercitar o painel administrativo e, por isso,
-- não precisam ocupar uma conta no Supabase Auth.
alter table public.professores alter column user_id drop not null;
alter table public.alunos alter column user_id drop not null;

create table if not exists public.audit_logs (
  id          bigint generated by default as identity primary key,
  actor_id    uuid,
  actor_email text not null default 'sistema',
  action      text not null check (action in ('insert', 'update', 'delete', 'reset', 'seed')),
  entity      text not null,
  entity_id   uuid,
  label       text,
  details     jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

alter table public.audit_logs enable row level security;

drop policy if exists "audit_logs: admin read" on public.audit_logs;
create policy "audit_logs: admin read"
on public.audit_logs for select to authenticated
using (public.is_fitpro_admin());

revoke all on table public.audit_logs from public, anon;
grant select on table public.audit_logs to authenticated;

create or replace function public.capture_fitpro_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row jsonb;
  v_id uuid;
  v_label text;
begin
  v_row := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  v_id := nullif(v_row ->> 'id', '')::uuid;
  v_label := coalesce(
    nullif(v_row ->> 'nome', ''),
    nullif(v_row ->> 'descricao', ''),
    nullif(v_row ->> 'categoria', '')
  );

  insert into public.audit_logs (
    actor_id,
    actor_email,
    action,
    entity,
    entity_id,
    label,
    details
  ) values (
    auth.uid(),
    coalesce(auth.jwt() ->> 'email', 'sistema'),
    lower(tg_op),
    tg_table_name,
    v_id,
    v_label,
    jsonb_build_object('origem', 'aplicacao')
  );

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

revoke all on function public.capture_fitpro_audit() from public;

do $$
declare
  v_table text;
begin
  foreach v_table in array array[
    'alunos', 'professores', 'planos', 'turmas', 'transacoes',
    'historico_peso', 'frequencia', 'treinos', 'exercicios', 'series_realizadas'
  ] loop
    execute format('drop trigger if exists audit_%I on public.%I', v_table, v_table);
    execute format(
      'create trigger audit_%I after insert or update or delete on public.%I for each row execute function public.capture_fitpro_audit()',
      v_table,
      v_table
    );
  end loop;
end;
$$;

create or replace function public.reset_test_environment()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_alunos bigint;
  v_professores bigint;
  v_planos bigint;
  v_turmas bigint;
  v_transacoes bigint;
  v_contas bigint;
begin
  if not public.is_fitpro_admin() then
    raise exception 'Apenas a administração pode reiniciar o ambiente de testes';
  end if;

  select count(*) into v_alunos from public.alunos;
  select count(*) into v_professores from public.professores;
  select count(*) into v_planos from public.planos;
  select count(*) into v_turmas from public.turmas;
  select count(*) into v_transacoes from public.transacoes;
  select count(*) into v_contas
  from auth.users
  where id <> auth.uid()
    and (
      email like 'aluno.%@fitpro.internal'
      or email like 'professor.%@fitpro.internal'
      or raw_user_meta_data ->> 'role' in ('aluno', 'professor')
    );

  delete from public.series_realizadas;
  delete from public.exercicios;
  delete from public.treinos;
  delete from public.frequencia;
  delete from public.historico_peso;
  delete from public.transacoes;
  delete from public.alunos;
  delete from public.turmas;
  delete from public.professores;
  delete from public.planos;

  delete from auth.users
  where id <> auth.uid()
    and (
      email like 'aluno.%@fitpro.internal'
      or email like 'professor.%@fitpro.internal'
      or raw_user_meta_data ->> 'role' in ('aluno', 'professor')
    );

  insert into public.audit_logs (
    actor_id, actor_email, action, entity, label, details
  ) values (
    auth.uid(),
    coalesce(auth.jwt() ->> 'email', 'sistema'),
    'reset',
    'ambiente_teste',
    'Ambiente de testes reiniciado',
    jsonb_build_object(
      'alunos', v_alunos,
      'professores', v_professores,
      'planos', v_planos,
      'turmas', v_turmas,
      'transacoes', v_transacoes,
      'contas_acesso', v_contas
    )
  );

  return jsonb_build_object(
    'alunos', v_alunos,
    'professores', v_professores,
    'planos', v_planos,
    'turmas', v_turmas,
    'transacoes', v_transacoes,
    'contasAcesso', v_contas
  );
end;
$$;

revoke all on function public.reset_test_environment() from public, anon;
grant execute on function public.reset_test_environment() to authenticated;

create or replace function public.generate_demo_data()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plano_basico uuid;
  v_plano_premium uuid;
  v_prof_ana uuid;
  v_prof_bruno uuid;
  v_turma_funcional uuid;
  v_turma_musculacao uuid;
  v_aluno_caio uuid;
  v_aluno_duda uuid;
  v_aluno_elisa uuid;
  v_aluno_felipe uuid;
  v_treino uuid;
begin
  if not public.is_fitpro_admin() then
    raise exception 'Apenas a administração pode gerar dados de demonstração';
  end if;

  if exists (select 1 from public.alunos)
     or exists (select 1 from public.professores)
     or exists (select 1 from public.planos)
     or exists (select 1 from public.turmas)
     or exists (select 1 from public.transacoes) then
    raise exception 'O gerador só pode ser usado quando o ambiente estiver vazio';
  end if;

  insert into public.planos (nome, preco, duracao, modalidades, beneficios, ativo)
  values ('[DEMO] Essencial', 99.90, '1 mês', array['Musculação'], array['Área de musculação', 'Avaliação inicial'], true)
  returning id into v_plano_basico;

  insert into public.planos (nome, preco, duracao, modalidades, beneficios, ativo)
  values ('[DEMO] Completo', 159.90, '1 mês', array['Musculação', 'Funcional'], array['Todas as modalidades', 'Avaliação mensal'], true)
  returning id into v_plano_premium;

  insert into public.professores (
    nome, cpf, telefone, email, horario, salario, especialidade, status, is_first_login
  ) values (
    '[DEMO] Ana Souza', '37128490523', '(00) 90000-0001', 'ana.professora@example.invalid', '07:00 - 15:00', 2800, 'Musculação', 'ativo', false
  ) returning id into v_prof_ana;

  insert into public.professores (
    nome, cpf, telefone, email, horario, salario, especialidade, status, is_first_login
  ) values (
    '[DEMO] Bruno Lima', '48615927391', '(00) 90000-0002', 'bruno.professor@example.invalid', '14:00 - 22:00', 3000, 'Funcional', 'ativo', false
  ) returning id into v_prof_bruno;

  insert into public.turmas (
    nome, modalidade, horario, dias_semana, capacidade, professor_id, sala, status
  ) values (
    '[DEMO] Funcional Manhã', 'Funcional', '08:00', array['Seg', 'Qua', 'Sex'], 12, v_prof_bruno, 'Sala 2', 'proxima'
  ) returning id into v_turma_funcional;

  insert into public.turmas (
    nome, modalidade, horario, dias_semana, capacidade, professor_id, sala, status
  ) values (
    '[DEMO] Musculação Tarde', 'Musculação', '17:00', array['Ter', 'Qui'], 15, v_prof_ana, 'Sala 1', 'proxima'
  ) returning id into v_turma_musculacao;

  insert into public.alunos (
    nome, cpf, telefone, email, idade, peso, plano_id, professor_id, status,
    turma_id, matricula_data, is_first_login, forma_pagamento, pagamento_status,
    vencimento, meta_semanal
  ) values (
    '[DEMO] Caio Martins', '72940615802', '(00) 91000-0001', 'caio.aluno@example.invalid', 24, 78.5,
    v_plano_premium, v_prof_bruno, 'ativo', v_turma_funcional, current_date - 35,
    false, 'Cartão', 'pago', current_date + 20, 3
  ) returning id into v_aluno_caio;

  insert into public.alunos (
    nome, cpf, telefone, email, idade, peso, plano_id, professor_id, status,
    turma_id, matricula_data, is_first_login, forma_pagamento, pagamento_status,
    vencimento, meta_semanal
  ) values (
    '[DEMO] Duda Rocha', '85321764026', '(00) 91000-0002', 'duda.aluna@example.invalid', 31, 64.2,
    v_plano_basico, v_prof_ana, 'ativo', v_turma_musculacao, current_date - 22,
    false, 'PIX', 'pago', current_date + 8, 4
  ) returning id into v_aluno_duda;

  insert into public.alunos (
    nome, cpf, telefone, email, idade, peso, plano_id, professor_id, status,
    turma_id, matricula_data, is_first_login, forma_pagamento, pagamento_status,
    vencimento, meta_semanal
  ) values (
    '[DEMO] Elisa Nunes', '19473852673', '(00) 91000-0003', 'elisa.aluna@example.invalid', 28, 70.0,
    v_plano_premium, v_prof_bruno, 'ativo', v_turma_funcional, current_date - 18,
    false, 'Boleto', 'atrasado', current_date - 3, 3
  ) returning id into v_aluno_elisa;

  insert into public.alunos (
    nome, cpf, telefone, email, idade, peso, plano_id, professor_id, status,
    turma_id, matricula_data, is_first_login, forma_pagamento, pagamento_status,
    vencimento, meta_semanal
  ) values (
    '[DEMO] Felipe Alves', '26584931773', '(00) 91000-0004', 'felipe.aluno@example.invalid', 36, 86.4,
    v_plano_basico, v_prof_ana, 'ativo', v_turma_musculacao, current_date - 5,
    false, 'PIX', 'pendente', current_date + 15, 3
  ) returning id into v_aluno_felipe;

  insert into public.historico_peso (aluno_id, data, peso) values
    (v_aluno_caio, current_date - 30, 80.1),
    (v_aluno_caio, current_date, 78.5),
    (v_aluno_duda, current_date - 20, 65.0),
    (v_aluno_duda, current_date, 64.2),
    (v_aluno_elisa, current_date - 15, 70.8),
    (v_aluno_elisa, current_date, 70.0),
    (v_aluno_felipe, current_date - 5, 86.4);

  insert into public.frequencia (aluno_id, data, presente) values
    (v_aluno_caio, current_date - 10, true),
    (v_aluno_caio, current_date - 7, true),
    (v_aluno_caio, current_date - 3, true),
    (v_aluno_duda, current_date - 9, true),
    (v_aluno_duda, current_date - 6, true),
    (v_aluno_duda, current_date - 2, true),
    (v_aluno_elisa, current_date - 8, true),
    (v_aluno_elisa, current_date - 4, false);

  insert into public.transacoes (tipo, categoria, descricao, valor, data, status, aluno_id) values
    ('receita', 'Mensalidade', '[DEMO] Mensalidade Caio', 159.90, current_date - 4, 'pago', v_aluno_caio),
    ('receita', 'Mensalidade', '[DEMO] Mensalidade Duda', 99.90, current_date - 3, 'pago', v_aluno_duda),
    ('receita', 'Mensalidade', '[DEMO] Mensalidade Elisa', 159.90, current_date - 2, 'atrasado', v_aluno_elisa),
    ('despesa', 'Energia', '[DEMO] Conta de energia', 380.00, current_date - 1, null, null);

  insert into public.treinos (aluno_id, nome, grupo)
  values (v_aluno_caio, '[DEMO] Treino A', 'Peito e tríceps')
  returning id into v_treino;

  insert into public.exercicios (treino_id, nome, series, reps, carga_sugerida) values
    (v_treino, 'Supino reto', 3, 10, 30),
    (v_treino, 'Tríceps na polia', 3, 12, 15);

  insert into public.audit_logs (
    actor_id, actor_email, action, entity, label, details
  ) values (
    auth.uid(),
    coalesce(auth.jwt() ->> 'email', 'sistema'),
    'seed',
    'ambiente_teste',
    'Dados de demonstração gerados',
    jsonb_build_object('alunos', 4, 'professores', 2, 'planos', 2, 'turmas', 2, 'transacoes', 4)
  );

  return jsonb_build_object(
    'alunos', 4,
    'professores', 2,
    'planos', 2,
    'turmas', 2,
    'transacoes', 4,
    'observacao', 'Registros DEMO não possuem conta de acesso'
  );
end;
$$;

revoke all on function public.generate_demo_data() from public, anon;
grant execute on function public.generate_demo_data() to authenticated;

commit;
